# Generated by Django 5.1.2 on 2024-12-11 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_playerprofile_number_playerprofile_pic_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerprofile',
            name='height',
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
