# Generated by Django 5.1.2 on 2024-12-18 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_playerprofile_height_playerprofile_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerprofile',
            name='pos',
            field=models.CharField(choices=[('Point Guard ', 'Point Guard'), ('Shooting Guard', 'Shooting Guard'), ('Small Forward', 'Small forward'), ('Power Forward', 'Power forward'), ('Center', 'Center')], max_length=50, null=True),
        ),
    ]
