# Generated by Django 5.1.2 on 2024-11-06 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='teams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Title')),
                ('desc', models.CharField(max_length=300, null=True, verbose_name='Desc')),
                ('password', models.CharField(max_length=10, verbose_name='Pass')),
                ('pic', models.ImageField(upload_to='media/')),
            ],
        ),
    ]
