# Generated by Django 5.1.2 on 2024-11-16 04:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teams',
            name='pic',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.CreateModel(
            name='drill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('desc', models.CharField(max_length=500, null=True, verbose_name='Desc')),
                ('pic', models.ImageField(blank=True, null=True, upload_to='img/')),
                ('video', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='team.teams')),
            ],
        ),
    ]
