# Generated by Django 5.1.2 on 2024-11-19 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_alter_teams_pic_drill'),
    ]

    operations = [
        migrations.CreateModel(
            name='img',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='si/')),
            ],
        ),
        migrations.CreateModel(
            name='pos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('PG ', 'Pg '), ('SG', 'Sg'), ('SF', 'Sf'), ('PF', 'Pf'), ('C', 'c'), ('OTHERS', 'Others')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='strat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('desc', models.CharField(max_length=500, null=True, verbose_name='Desc')),
                ('images', models.ManyToManyField(null=True, related_name='strategy', to='team.img')),
                ('pos', models.ManyToManyField(null=True, related_name='strategy', to='team.pos')),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='team.teams')),
            ],
        ),
    ]
