# Generated by Django 5.1.2 on 2024-11-19 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0004_remove_strat_images_img_strat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='img',
            name='strat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='team.strat'),
        ),
    ]
