# Generated by Django 5.1.2 on 2024-11-20 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0005_alter_img_strat'),
    ]

    operations = [
        migrations.CreateModel(
            name='diet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('S', 'Saturday'), ('SU', 'Sunday'), ('M', 'Monday'), ('T', 'Tuesday'), ('W', 'Wednesday'), ('TH', 'Thursday'), ('F', 'Friday')], max_length=50)),
                ('meal', models.CharField(choices=[('D', 'Dinner'), ('B', 'Breakfast'), ('L', 'Lunch'), ('BG', 'Pre Game'), ('AG', 'Post Game'), ('S', 'Snack')], max_length=50)),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('desc', models.CharField(max_length=500, null=True, verbose_name='Desc')),
            ],
        ),
    ]
