# Generated by Django 5.1.2 on 2024-11-20 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0006_diet'),
    ]

    operations = [
        migrations.AddField(
            model_name='diet',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='team.teams'),
        ),
    ]
