# Generated by Django 5.1.2 on 2024-12-02 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0007_diet_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='news',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('desc', models.CharField(max_length=500, null=True, verbose_name='Desc')),
                ('pic', models.ImageField(blank=True, null=True, upload_to='img/')),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='team.teams')),
            ],
        ),
    ]
