# Generated by Django 5.1.2 on 2024-12-02 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0008_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='desc',
            field=models.CharField(max_length=2000, null=True, verbose_name='Desc'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Title'),
        ),
    ]
