# Generated by Django 5.1.2 on 2024-12-11 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0009_alter_news_desc_alter_news_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='pic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='sd/')),
                ('drill', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='team.drill')),
            ],
        ),
    ]
