# Generated by Django 5.1.2 on 2024-12-11 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0010_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drill',
            name='pic',
        ),
    ]
