# Generated by Django 5.1.2 on 2024-12-02 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0002_matches_isplayed_matches_sc1_matches_sc2'),
    ]

    operations = [
        migrations.CreateModel(
            name='analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=500, null=True, verbose_name='Desc')),
                ('pic', models.ImageField(blank=True, null=True, upload_to='img/')),
                ('video', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matche', to='match.matches')),
            ],
        ),
    ]
