# Generated by Django 5.1.2 on 2024-12-02 18:26
import django.db.models.deletion
from django.db import migrations, models
class Migration(migrations.Migration):
    dependencies = [
        ('match', '0003_analysis'),
    ]
    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='desc',
            field=models.CharField(max_length=1000, null=True, verbose_name='Desc'),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match', to='match.matches'),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='p1/'),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='v1/'),
        ),
    ]